package GUI;

import civitas.Casilla;

public class CasillaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCasilla = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("CASILLA ACTUAL:");
        add(jLabel1);

        jTextFieldCasilla.setEditable(false);
        jTextFieldCasilla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextFieldCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCasillaActionPerformed(evt);
            }
        });
        add(jTextFieldCasilla);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCasillaActionPerformed

    Casilla casilla;

    public void setCasilla(Casilla actual) {
        this.casilla = actual;
        
        jTextFieldCasilla.setText(casilla.getNombre());
        
        repaint();
        revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCasilla;
    // End of variables declaration//GEN-END:variables
}
