package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alejandro Rosales Cantero
 */
public class PropiedadDialog extends javax.swing.JDialog {


    private int propiedadElegida;
    
    /**
     * Creates new form PropiedadDialog
     */
    public PropiedadDialog(java.awt.Frame parent, boolean modal, Jugador jugadorActual) {
        super(parent, modal);
        initComponents();
        
        propiedadElegida = -1;
        
         DefaultListModel propiedades = new   DefaultListModel<>();
         ArrayList<CasillaCalle> opciones = jugadorActual.getPropiedades();
          
         for(CasillaCalle calle : opciones){
             propiedades.addElement(calle.getNombre());
         }
         
         ListaPropiedades.setModel(propiedades);
         setVisible(true);
         
         repaint();
         revalidate();
    }

    public int getPropiedadElegida() {
        return propiedadElegida;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPropiedades = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPropiedades = new javax.swing.JList<>();
        BotonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelPropiedades.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        LabelPropiedades.setText("PROPIEDADES:");

        ListaPropiedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPropiedadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPropiedades);

        BotonSeleccionar.setText("Seleccionar");
        BotonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonSeleccionar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(LabelPropiedades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionarActionPerformed
        // TODO add your handling code here:
        if(propiedadElegida != -1){
            dispose();
        }
    }//GEN-LAST:event_BotonSeleccionarActionPerformed

    private void ListaPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPropiedadesMouseClicked
        // TODO add your handling code here:
        propiedadElegida = ListaPropiedades.getSelectedIndex();
    }//GEN-LAST:event_ListaPropiedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSeleccionar;
    private javax.swing.JLabel LabelPropiedades;
    private javax.swing.JList<String> ListaPropiedades;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
